<?php
return [
	'QUESTION_CLASS_AGENT' => 1,
	'QUESTION_CLASS_SERVICE' => 2,
	'QUESTION_CLASS_ENVIRONMENT' => 3,
	'IF_TOP_AGENTS' => 1,
	'IF_BOTTOM_AGENTS' => -1,
	'FILTER_BY_WEEK' => 0,
	'FILTER_BY_MONTH' => 1,
];